trunk-version = "*"

[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
inject_scripts = true
frozen = false
locked = false
minify = "never"
no_sri = false

[watch]
watch = ["css/"]
ignore = []

[serve]
addresses = ["127.0.0.1"]
port = 8082
open = false
no_spa = false
no_autoreload = false
no_error_reporting = false
ws_protocol = "ws"

[clean]
dist = "dist"
cargo = false

# [tools]
# sass = "1.69.5"
# wasm_bindgen = "0.2.89"
# wasm_opt = "version_116"
# tailwindcss = "3.3.5"


# [[proxy]]
# backend = "ws://localhost:9000/api/ws"
# ws = true

# [[proxy]]
# rewrite = "/api/v1/"
# backend = "http://localhost:9000/"

# [[proxy]]
# backend = "http://localhost:9000/api/v2/"

# [[proxy]]
# backend = "https://localhost:9000/api/v3/"
# insecure = true

# [[proxy]]
# backend = "https://172.16.0.1:9000/api/v3/"
# no_system_proxy = true

# [[hooks]]
# stage = "pre_build"
# command = "echo"
# command_arguments = ["Hello", "Trunk!"]

# [[hooks]]
# stage = "build"
# command = "sh"
# command_arguments = ["-c", "echo Staging directory: $TRUNK_STAGING_DIR"]

# [[hooks]]
# stage = "post_build"
# command = "ls"