[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["format"]

[tasks.fresh]
command = "cargo"
args = ["run",
    "--fresh=true"
    ]
dependencies = ["format"]

[tasks.watch]
command = "cargo"
args = ["watch",
    "-w",
    "./src",
    "-w",
    "./data",
    "-w",
    "./Cargo.toml",
    "-x",
    "run"
    ]
dependencies = ["format"]
